name: Run Tests

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main, refactor/* ]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "CODEOWNERS"
      - "LICENSE"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Checkstyle:
    permissions:
      id-token: write
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest checkstyleTestFixtures

  Javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main

      - name: Run Javadoc
        run: ./gradlew javadoc

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - run: ./gradlew testClasses
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: .

  Unit-Tests:
    needs: [ Build ]
    runs-on: ubuntu-latest
    env:
      JACOCO: true
    steps:
      - uses: actions/download-artifact@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: Run unit tests
        uses: eclipse-edc/.github/.github/actions/run-tests@main
        with:
          command: |
            cd build
            chmod +x gradlew
            ./gradlew test jacocoTestReport

  Postgresql-Integration-Tests:
    needs: [ Build ]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.2
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/download-artifact@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: Postgresql Tests
        uses: eclipse-edc/.github/.github/actions/run-tests@main
        with:
          command: |
            cd build
            chmod +x gradlew
            ./gradlew test -DincludeTags="PostgresqlIntegrationTest"

  End-To-End-Tests:
    needs: [ Build ]
    env:
      JACOCO: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: End to End Tests
        uses: eclipse-edc/.github/.github/actions/run-tests@main
        with:
          command: |
            cd build
            chmod +x gradlew
            ./gradlew test jacocoTestReport -DincludeTags="EndToEndTest"

  Component-Tests:
    needs: [ Build ]
    env:
      JACOCO: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: Component Tests
        uses: eclipse-edc/.github/.github/actions/run-tests@main
        with:
          command: |
            cd build
            chmod +x gradlew
            ./gradlew test jacocoTestReport -DincludeTags="ComponentTest"

  API-Tests:
    needs: [ Build ]
    env:
      JACOCO: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: Api Tests
        uses: eclipse-edc/.github/.github/actions/run-tests@main
        with:
          command: |
            cd build
            chmod +x gradlew
            ./gradlew test jacocoTestReport -DincludeTags="ApiTest"

  Upload-Test-Report:
    needs:
      - API-Tests
      - Component-Tests
      - End-To-End-Tests
      - Postgresql-Integration-Tests
      - Unit-Tests

    permissions:
      checks: write
      pull-requests: write

    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "**/test-results/**/*.xml"

  Upload-Coverage-Report-To-Codecov:
    needs:
      - API-Tests
      - Unit-Tests
      - Component-Tests
      - End-To-End-Tests

    runs-on: ubuntu-latest
    if: always()
    steps:
      # Sources are needed for Codecov report
      - uses: actions/download-artifact@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: CodeCov
        uses: codecov/codecov-action@v4
